export interface AuditSummaryReportModel{
    branch: string,
    amC_INCENTIVE_HOLD: number,
    beyonD_AMC_POLICY: number,
    claimS_SELF_REGISTRATION: number,
    datA_AUDIT: number,
    gaS_OVERCHARGING: number,
    duplicatE_DATA: number,
    estimatE_OW_AMC: number,
    extrA_FILTER_AMC: number,
    insidE_FILTERS_IW_WTY: number,
    modeL_CHANGE: number,
    ooW_CLAIMS: number,
    parT_IN_LABOR: number,
    posT_AMC_30_DAYS: number,
    rF_SPECIAL_MODEL: number,
    suspiciouS_AMC: number,
    wronG_PART_CONSUMPTION: number,
    multiplE_CLOSURE_SAME_DAY: number,
    lgC_PART_REJECTION: number,
    lgC_NON_PART_REJECTION: number,
    cancellatioN_CLAIM_RECOVERY: number,
    multiplE_BRACKET: number,
    granD_TOTAL: number
}